### ISSUE TITLE
On update_item when using "IN" Conditional Write Operator, AttributeValueList gets only the last item of the list.

### ISSUE THREAD

**Issue by lita** [jlafon/PynamoDB#102]
I am trying to do an update_item with the following parameters

`model.update_item("status", "delivered", status__in=['queued', 'sending', 'sent'])`
The model's current status is 'queued'. So this should work. However, I get a UpdateError. When I look at the logs, this is what the AWS json is generating.

`{'status': {'ComparisonOperator': 'IN', 'AttributeValueList': [{'S': u'sent'}]}}`

Shouldn't the AttirbuteValueList have all three items in it? It seems to be only putting the last item in the list.

**Comment by jpinner-lyft** [comment]
From the documentation at http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-Expected

> IN : Checks for matching elements within two sets.
AttributeValueList can contain one or more AttributeValue elements of type String, Number, or Binary (not a set type). These attributes are compared against an existing set type attribute of an item. If any elements of the input set are present in the item attribute, the expression evaluates to true.

It would be nice if the library handled this by creating an entry in the list for each attribute passed in.
