### ISSUE TITLE
BatchWriteItem: UnprocessedItems is not handled correctly

### ISSUE THREAD

**Issue by Sazpaimon** [jlafon/PynamoDB#103]
When a BatchWriteItem call returns UnprocessedItems, Pynamo incorrectly assumes that it's a dict of dict of dicts, when it's actually a dict of list of dicts. The current behavior causes an error along the lines of "list has no attribute iteritems". I think changing `for item in six.itervalues(item_mapping):` to a simple `for item in item_mapping` (as is the case with UnprocessedKeys) would resolve the problem.

**Comment by beeradb** [comment]
#120 was opened to fix this

**Comment by danielhochman** [comment]
Fixed with #114
