### ISSUE TITLE
Invalid range for parameter Limit

### ISSUE THREAD

**Issue by maryokhin** [jlafon/PynamoDB#111]
Hello, we are running based on `devel` branch because we are relying on an unreleased session configuration feature. Until we updated to or past commit dd726cebe477bf6103ea55052db2f5331ed03081 everything was fine. For some reason this commit gives us a stacktrace with the same code when using Limit.

```
pynamodb.exceptions.QueryError: Failed to query items: Parameter validation failed:
Invalid range for parameter Limit, value: -16, valid range: 1-inf
```

Since we have 0 experience with PynamoDB we though maybe you can give us a hint on how this commit might affect us. Currently we're running a fork based on `devel` with this commit reverted.

**Comment by danielhochman** [comment]
fixed in #123 

thanks for the report!
