### ISSUE TITLE
Add support for condition expressions

### ISSUE THREAD

**Issue by behos** [jlafon/PynamoDB#116]
Hello,

I was unable to find how to perform a conditional write with condition expressions 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html#Expressions.SpecifyingConditions.ConditionExpressions

Looking through the code, it seems that this is not supported at the moment.

Are there any plans to support this?

George

**Comment by danielhochman** [comment]
Hi George,

Conditional writes are supported. Please see documentation at http://pynamodb.readthedocs.io/en/latest/conditional.html#conditional-model-save

**Comment by behos** [comment]
I was actually referring to condition expressions which allow functions like attribute_not_exists().

However, I was able to do what I need using the current functionality, so I'm happy for this issue to be closed.
