### ISSUE TITLE
list attribute support

### ISSUE THREAD

**Issue by maloky** [jlafon/PynamoDB#122]
Hi, 

I was looking up a built in attribute to store a list, as the NumberSet doesn't allow duplicates, but could'n find it out.
Am i missing something? Do i have to create a custom attribute?
Thanks

**Comment by digitizdat** [comment]
I just noticed this myself as well. I think PynamoDB doesn't support list attributes yet. Right now there is support for Unicode, Binary, JSON, Number, Set, and UTC Datetime attributes.

**Comment by digitizdat** [comment]
@maloky, I've created a new pull request that adds a new attribute called NumberListAttribute. Please check it out and see if it's working for you.

https://github.com/jlafon/PynamoDB/pull/131

**Comment by maloky** [comment]
@digitizdat Nice. I tried almost the same thing but were getting problems on serialization. Gone give a try but seems good. Thanks

**Comment by digitizdat** [comment]
@maloky After a little more work on my project, I realized I also needed lists of lists of numbers, which I've added support for in this pull request (recursive list support), so if you can use that too, please pull this set of commits again and let me know how it goes for you.

Cheers!

**Comment by jmphilli** [comment]
Hey! We just added this and MapAttributes with [this](https://github.com/jlafon/PynamoDB/commit/50fa1607a1de9f8500722d04855fcf0971f7d262) commit

**Comment by jmphilli** [comment]
can we close this?

**Comment by maloky** [comment]
yep..thanks so much for the effort.

**Comment by karteek-paruchuri** [comment]
Why `ListAttribute` isn't of Unicode format?
