### ISSUE TITLE
How can I specify model table_name and region at runtime?

### ISSUE THREAD

**Issue by stevecox** [jlafon/PynamoDB#177]
In my environment I use table prefix names to specify different environments (such as test_Table, stage_Table, prod_Table, etc).  Rather than defining the table_name and region/host in the Meta class inside of each model, is there a way to specify these at runtime?

**Comment by bkruger99** [comment]
I'm far from a python expert, but you could pass in region at runtime.  

As far as the dynamic calling, perhaps: http://stackoverflow.com/questions/4246000/how-to-call-python-functions-dynamically would be useful.

```
class foo: 
    def __init__(self, region, *field):
        self.region = region
        master = ddb.MasterInstance()
        master.Meta.region = self.region
```

**Comment by yfilali** [comment]
@stevecox Have you tried something like this?

`
def table_name(name):
    import os
    return os.environ.get('ENV', 'test'] + '_' + name

def table_region():
    return os.environ.get('DB_REGION', 'us-west-2')

class MyModel(PynamoModel):
    class Meta:
        table_name = table_name('mymodel')
        region = table_region()
`

or better yet, you could inherit your own Model class from PynamoModel. It would let you do things that generic in the parent Model class. For example setting the id automatically if you don't have one:

`
class Model(PynamoModel):
    class Meta:
        read_capacity_units = 1
        write_capacity_units = 1
        host = "http://localhost:8000" if os.environ.get("ENV") == "local" else None
        region = os.environ.get("REGION", "us-west-2")
`

Then your model classes could look like:
`
class Foo(Model):
    class Meta(Model.Meta):
        table_name = table_name("foo")

    id = UnicodeAttribute(hash_key=True)
    bar = UnicodeAttribute(null=False)

`

**Comment by stevecox** [comment]
@yfilali These are great suggestions, thank you!  I wonder if there are others with a similar issue where somehow adding a parameter to the model at instantiation would be more convenient.

**Comment by lonsdale8734** [comment]
@yfilali Have you test your demo? In my development, Meta.host cannot be set to None. And I have another question, global secondary index seems cannot be inheritted.

**Comment by laurarp** [comment]
@stevecox i made this overriding the contructor and using the environment variables

public function __construct()
    {
        $this->table = env('DB_PREFIX').'users';
    }

**Comment by ikonst** [comment]
This is exactly how we do it here at Lyft (a different table name for staging vs. production), and we follow that same [Store config in environment](https://12factor.net/config) pattern.

settings.py
```
FOO_BAR_TABLE_NAME = os.environ['FOO_BAR_TABLE_NAME']
```

foo_bar.py
```
class FooBar(Model):
  class Meta:
    table_name = settings.FOO_BAR_TABLE_NAME
```

**Comment by laimonassutkus** [comment]
@ikonst sometimes even this is not dynamic enough. 

For example:
Imagine you have one DynamoDB table per customer. Only when have received an HTTP request with, let's say, an API KEY, you can determine which table to use. OS-level variables will not help you here.

**Comment by laimonassutkus** [comment]
@ikonst anyways... I have created a few wrappers around pynamodb that extend functionality greatly. Feel free to review and give your opinion: [B.DynamoDbCommon](https://github.com/Biomapas/B.DynamoDbCommon). I am especially proud in:

- FernetAttribute (Fernet algorithm to encrypt data)
- KmsAttribute (Using AWS KMS CMK to encrypt data)
- ModelTypeFactory (Solves this thread's problems of dynamic tables)
- PynamoDBListResult (Solves pagination headache)
