### ISSUE TITLE
MapAttribute raises error on model save

### ISSUE THREAD

**Issue by yedpodtrzitko** [jlafon/PynamoDB#182]
Hi,
I have a problem with the new `MapAttribute`. Here's an example:

```python
class MapModel(Model):
    class Meta:
        table_name = 'test_map'

    id = UnicodeAttribute(hash_key=True)
    map_attribute = MapAttribute(default={})

map = MapModel()
map.create_table(read_capacity_units=1, write_capacity_units=1)

instance = MapModel('foo', map_attribute={'foo': 'bar'})
instance.save()
```

here's the traceback:
```
File "test.py", line 19, in create
    instance.save()
  File "/Users/yed/tmp/venv/lib/python2.7/site-packages/pynamodb/models.py", line 365, in save
    args, kwargs = self._get_save_args()
  File "/Users/yed/tmp/venv/lib/python2.7/site-packages/pynamodb/models.py", line 1035, in _get_save_args
    serialized = self._serialize(null_check=null_check)
  File "/Users/yed/tmp/venv/lib/python2.7/site-packages/pynamodb/models.py", line 1207, in _serialize
    if not value.validate():
AttributeError: 'dict' object has no attribute 'validate'
```

Am I using it wrong? //cc @jmphilli

**Comment by jmphilli** [comment]
@yedpodtrzitko -- thanks for reporting!
I'm not sure what to do in this case... 
It doesn't really make sense to have a raw `MapAttribute`. You can't leverage any of the type checking that we added if you don't have a structured type. 

The idea is really to extend `MapAttribute` with a class of your own.
There are some examples [here](https://github.com/jlafon/PynamoDB/blob/devel/examples/office_model.py#L5)

That said, I opened a PR to add some better messaging [here](https://github.com/jlafon/PynamoDB/pull/183)

**Comment by jmphilli** [comment]
can we close this because we patched it [here](https://github.com/jlafon/PynamoDB/pull/186)
