### ISSUE TITLE
raw MapAttribute does not work as expected

### ISSUE THREAD

**Issue by yedpodtrzitko** [jlafon/PynamoDB#191]
@jmphilli looks like you were right that there is more to do to support a raw `MapAttribute`.
I've tried to replace my fork of PynamoDB with the vanilla version today, and I've run into a problem.

in `Model.from_raw_data()` (which is called eg. in `Model().get()`), there's an `if` statement for `MapAttribute`, which sets the value of the model's attribute to an instance of `MapAttribute`. That works fine for the inherited `MapAttribute` (since you want to access its nested attributes only), but it does not work for the raw `MapAttribute` itself, since you need access to its value directly. Example.
```python
class MyModel(Model):
    id = UnicodeAttribute(hash_key=True)
    map_attr = MapAttribute(default={'foo': 'bar'})

instance = MyModel.get('pk')
instance.map_attr['foo'] # does not work
```
^here you can't access the value of `foo`, since `map_attr` is an instance of `MapAttribute` instead of a dict.

This would be a dummy solution for dealing with both raw `MapAttribute` and inherited one too.

```diff
def get_raw_data():
...
    if attr:
        deserialized_attr = attr.deserialize(attr.get_value(value))
-        if isinstance(attr, MapAttribute):
+        # use an instance of MapAttribute only for inherited classes
+        if isinstance(attr, MapAttribute) and not type(attr) == MapAttribute:
            deserialized_attr = type(attr)(**deserialized_attr)
        kwargs[name] = deserialized_attr
```

**Comment by jmphilli** [comment]
https://github.com/jlafon/PynamoDB/pull/192
