### ISSUE TITLE
Permission to add PynamoDB stubs to Typeshed?

### ISSUE THREAD

**Issue by rowillia** [jlafon/PynamoDB#209]
Howdy,

I'd like to add stubs for PynamoDB to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

Thanks, let me know if you have any questions

**Comment by jmphilli** [comment]
@danielhochman

**Comment by danielhochman** [comment]
+1

how do we ensure stubs stay up to date with any interface changes?

**Comment by rowillia** [comment]
@danielhochman For now I'll be responsible for keeping them up to date.
