### ISSUE TITLE
case insensitive queries?

### ISSUE THREAD

**Issue by pjz** [jlafon/PynamoDB#214]
Is there a way to do case insensitive string queries?  Or do I need to hack in something like 'save an all-lowercase version of the field also, and do a lowercased-query on that field instead' ?

**Comment by yedpodtrzitko** [comment]
afaik no - DynamoDB is a key-value storage, so it does not dispose such features as traditional SQL databases.

**Comment by pjz** [comment]
I was hoping there was something in index construction or elsewhere that I'd missed.
