### ISSUE TITLE
Connection refused when used in lambda

### ISSUE THREAD

**Issue by sv1jsb** [jlafon/PynamoDB#227]
Hi,

I am trying to use PynamoDB models with a lambda function,
but the model gets 'Connection refused' error from DynamoDB server.

My lambda function has correct role set.
I can connect to DynamoDB with boto3 using:
`dynamodb = boto3.resource('dynamodb')`
`mytable = dynamodb.Table('MyTable')`
`row = mytable.get_item(Key={'hash': hash_value, 'sort': sort_value})['Item']`

I am guessing that PynamoDB is always trying to connect using
the `.aws` credentials, which are not present at the lambda deployment.

Is there a way to a configure PynamoDB model to use the supplied roles and policies
and not `.aws` credentials?

Best regards,
Andreas

**Comment by brandond** [comment]
Connection refused indicates that it can't connect to the dynamodb service endpoint, not that it doesn't have proper credentials. Are you using Lambda with a VPC endpoint and security group that doesn't allow access to the service endpoint?

**Comment by sv1jsb** [comment]
Hi brandond,

Thanks for the reply.
There are no VPC or security groups.
Just plain lambda function.
Nevertheless, exactly the same function with boto3 is successful as  mentioned before.

Best regards,
Andreas

**Comment by brandond** [comment]
Can you set the root logger level to DEBUG and post the output?

**Comment by sv1jsb** [comment]
Hi brandond,

Thank you for your help.
It seems that the `region` attribute in Model's Meta is needed.
It tried to connect to us-east-1 by default.

I am closing this issue.

Best regards,
Andreas
