### ISSUE TITLE
Question: How to do pagination?

### ISSUE THREAD

**Issue by ccverak** [jlafon/PynamoDB#231]
I wasn't able to find any docs on how to perform pagination. Please, can you help me with an example? I want to provide an API with pagination caps
Thanks.

**Comment by yedpodtrzitko** [comment]
It's not possible atm. It's also unlikely there will be a support for pagination caps in future - see how DynamoDB handles pagination (only the forward-direction via `LastEvaluatedKey`, see http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#Pagination )

**Comment by ccverak** [comment]
Thanks, is there a way to pass the LastEvaluetedKey to a query operation on a Pynamodb model? I don't see it in the docs.

**Comment by yedpodtrzitko** [comment]
https://github.com/jlafon/PynamoDB/pull/226

**Comment by ccverak** [comment]
Thanks!
