### ISSUE TITLE
Add support for new JSON document datatypes

### ISSUE THREAD

**Issue by BCVisin** [jlafon/PynamoDB#38]
https://aws.amazon.com/blogs/aws/dynamodb-update-json-and-more/
http://www.allthingsdistributed.com/2014/10/document-model-dynamodb.html

**Comment by erikcw** [comment]
I tend to agree with @dcosson.  The `map` type should be a completely separate `Attribute` type from `JSONAttribute`.  This would eliminate the backwords compatibility issues as well as preserving JSON persistence for those who may not want to use a `map` for whatever reason.

**Comment by dukedougal** [comment]
I'd suggest making it as compatible with the current version of DynamoDB as possible and you should be prepared to break compatibility with old versions of PynamoDB.  Compatibility with DynamoDB is more important than compabilityy with PynamoDB.

**Comment by joshowen** [comment]
I agree that it makes sense to track the latest DynamoDB features in JSONAttribute, and rename the existing class `LegacyJSONAtrtribute` and list it as a breaking change.

@jlafon @danielhochman any thoughts?

**Comment by kapad** [comment]
@jlafon Is this in the feature pipeline? Is there any timeline around this feature?
Also are you aware of any forks that may have implemented the dynamo document types?

**Comment by RixKa** [comment]
I like pynamodb however due to it's lack of support for Maps and Lists we can't use it.

I sincerely hope that there is an update looking to make use of Maps and List sometime soon.

**Comment by kapad** [comment]
@RixKa I've made some changes to support Lists and Maps. It's not as good and intuitive as I'd like, but it works to an extent. Would love to get a PR to add full support for Lists and Maps. I don't think there is a plan to add support in this repo. 

https://github.com/kapad/PynamoDB

**Comment by jmphilli** [comment]
hi everyone, @danielhochman and I are working on adding this to a new version of pynamo. we're currently testing an RC so hopefully we can have a release soon.

**Comment by jmphilli** [comment]
so we added map + list in 2.0.0 -- can we close this?
