### ISSUE TITLE
Error doing conditional updates

### ISSUE THREAD

**Issue by dlg** [jlafon/PynamoDB#42]
I'm trying to do conditional updates (testing against dynalite if that causes any issues).

I want to add something to a UnicodeSet if the row exists, but not to insert it if it doesn't.

If I don't do a conditional update
model.MyTable(user_id).update_item('my_set_field', ['value'], action='add')
it works fine.

If I make it conditional
model.MyTable(user_id).update_item('my_set_field', ['value'], user_id__null=False, action='add')
I get 

File "/path/lib/python2.7/site-packages/pynamodb/connection/base.py", line 639, in update_item
    raise UpdateError("Failed to update item: {0}".format(response.content))
UpdateError: Failed to update item: {"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: 'Exists' is set to null. 'Exists' must be set to false when no Attribute value is specified"}

I may just be doing this wrong--if-so, sorry!

**Comment by mhart** [comment]
As with #41 I suspect this was with an older version of dynalite, pre v0.4.0 when the DynamoDB conditional API changed.

@dig what version of dynalite were you using?
