### ISSUE TITLE
Results count(*)

### ISSUE THREAD

**Issue by user0007** [jlafon/PynamoDB#49]
Is there any chance to add option to return count of records instead of list of records? Dynamodb (and boto also) supports this behaviour - http://boto.readthedocs.org/en/latest/ref/dynamodb.html

Thanks.

**Comment by cshoe** [comment]
Hey @user0007. I'm looking for the same functionality. I started a fork to address this (no promises on finishing) but in the meantime, I found a pretty simple workaround.

```python
from pynamodb.connection import TableConnection
conn = TableConnection('table_name')
conn.query('somehashkeyvalue', select='COUNT')['ScannedCount']
```

The caveat is that I'm not 100% sure that paging is taken care of with this approach. I'm currently looking into whether or not something like the [while loop](https://github.com/boto/boto/blob/develop/boto/dynamodb2/table.py#L1125) in boto is necessary.

**Comment by user0007** [comment]
Hello @cshoe ,

I wrote `count` method and added it to the model's class.

    @classmethod
    def count(cls, hash_key, consistent_read=False, index_name=None,
              **filters):

        cls._get_indexes()
        if index_name:
            hash_key = cls._index_classes[index_name].\
                _hash_key_attribute().serialize(hash_key)
            key_attribute_classes = \
                cls._index_classes[index_name]._get_attributes()
            non_key_attribute_classes = cls._get_attributes()
        else:
            hash_key = cls._serialize_keys(hash_key)[0]
            non_key_attribute_classes = AttributeDict()
            key_attribute_classes = AttributeDict()
            for name, attr in cls._get_attributes().items():
                if attr.is_range_key or attr.is_hash_key:
                    key_attribute_classes[name] = attr
                else:
                    non_key_attribute_classes[name] = attr
        key_conditions, query_filters = cls._build_filters(
            QUERY_OPERATOR_MAP,
            non_key_operator_map=QUERY_FILTER_OPERATOR_MAP,
            key_attribute_classes=key_attribute_classes,
            non_key_attribute_classes=non_key_attribute_classes,
            filters=filters)
        data = cls._get_connection().query(
            hash_key,
            index_name=index_name,
            consistent_read=consistent_read,
            key_conditions=key_conditions,
            query_filters=query_filters,
            select='count',
        )
        cls._throttle.add_record(data.get(CONSUMED_CAPACITY))
        return data.get('Count', 0)


    >> MyModel.count(hash, some_filter=value)
    123

**Comment by cshoe** [comment]
Nice. Thanks, @user0007
