### ISSUE TITLE
Bug in base.py range key is not sent out if range key is 0 

### ISSUE THREAD

**Issue by kyangmove** [jlafon/PynamoDB#62]
In case the value of range_key is 0 it will be false.

 if range_key: 

def get_identifier_map(self, hash_key, range_key=None, key=KEY):
        """
        Builds the identifier map that is common to several operations
        """
        kwargs = {
            pythonic(key): {
                self.hash_keyname: {
                    self.get_attribute_type(self.hash_keyname): hash_key
                }
            }
        }
        if range_key:
            kwargs[pythonic(key)][self.range_keyname] = {
                self.get_attribute_type(self.range_keyname): range_key
            }
        return kwargs

**Comment by jlafon** [comment]
This should have been fixed in 96a9900d
