### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by antoinemenini** [jlafon/PynamoDB#67]
Hi,
I'm trying to create a table using pynamodb. Here is the code:

```
class KIndex(DDBModel):
    class Meta:
        table_name = 'k_index'
        write_capacity_units = 10
        read_capacity_units = 10

    profile_id = UnicodeAttribute(hash_key=True)
    date = UnicodeAttribute(range_key=True)
    value = UnicodeAttribute()

def create_tables():
    if not KIndex.exists():
        KIndex.create_table(wait=True)
```

Unfortunately, when I run the function create_tables(), I get the following exception:

```
pynamodb/connection/base.py in get_meta_table(self, table_name, refresh)
    270                 if e.response['Error']['Code'] == 'ResourceNotFoundException':
    271                     raise TableDoesNotExist(e.response['Error']['Message'])
--> 272             self._tables[table_name] = MetaTable(data.get(TABLE_KEY))
    273         return self._tables[table_name]
    274

UnboundLocalError: local variable 'data' referenced before assignment
```

What did I do wrong?

**Comment by jlafon** [comment]
Looks like it was a bug introduced in the last release, not your fault.

**Comment by antoinemenini** [comment]
Thank you

**Comment by antoinemenini** [comment]
I think the problem is more deep than that because now the try in base.py at line 262 doesn't succeed but nothing happens and therefore the statement `return self._tables[table_name]` raises a keyerror. Do you want me to help you debug it?

**Comment by jlafon** [comment]
Yes, that would be great. My suspicion is that a ClientError is raised, but that the error is not a ResourceNotFoundException. I'm going to push a small change that reraises the original exception.

**Comment by antoinemenini** [comment]
Indeed: 
```
ClientError: An error occurred (UnrecognizedClientException) when calling the DescribeTable operation: The security token included in the request is invalid.
```

I'll tweak the code a little bit to print the error message from the client.

**Comment by antoinemenini** [comment]
Ok in the end it seems that the error is quite straightforward: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html
