### ISSUE TITLE
Configurable timeout for method calls

### ISSUE THREAD

**Issue by ParthGandhi** [jlafon/PynamoDB#81]
On connection errors it retries for about 30 sec. Is there a way to configure that?

**Comment by danielhochman** [comment]
I ran into the same issue. It's possible to override botocore's retry handling by copying [_retry.json](https://github.com/boto/botocore/blob/4843789b29e8d83a3c08247d6f3fed9c6f086878/botocore/data/_retry.json#L63) into [~/.aws/models/_retry.json](https://github.com/boto/botocore/blob/9ec1570694999de23e0da87f31d33072d6e07e90/botocore/loaders.py#L197-L198) and modifying the policy for DynamoDB.

Also, the current code on the development branch circumvents botocore for request handling. So as of next release, you will no longer need this override. Any retry handling will need to be built into your application or [a future version of PynamoDB](https://github.com/jlafon/PynamoDB/pull/80).

**Comment by danielhochman** [comment]
Release 1.4.3 now has #72. There is no retry handling under the hood in 1.4.3.

**Comment by ParthGandhi** [comment]
@danielhochman Thanks! Closing this, but lets discuss further in #80 .
