### ISSUE TITLE
NumberAttribute stored as string?

### ISSUE THREAD

**Issue by erikcw** [jlafon/PynamoDB#85]
Wouldn't it be more efficient use of disk space to store `NumberAttribute` types as `ints` instead of `String`s in Dynamo?  Any particular reason why they are being json encoded currently?

**Comment by danielhochman** [comment]
The DynamoDB API accepts strings for Number values for precision reasons: 
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataFormat.html#JSONTransport
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModel.DataTypes
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html

The key in an AttributeValue pair ("N", "S", etc) specifies what the datatype is. Internally, it's up to DynamoDB as to how they want to store it. I'm pretty sure DynamoDB stores Numbers as strings internally and just uses Number to determine how to sort, apply range filters, etc, but don't quote me on that.

**Comment by jlafon** [comment]
Yes @danielhochman is correct. Numbers have to serialized to JSON because that is what DynamoDB requires.
