### ISSUE TITLE
Updating item issues - specifically delete/remove

### ISSUE THREAD

**Issue by chrisjones-brack3t** [jlafon/PynamoDB#90]
So I started writing my own quick wrapper for DynamoDB earlier in the week. During the nightmare of trying to figure out how to update attributes within an item I came across your package. The model, awesome. Need to create an item, easy. Delete an item, easy. Remove an attribute of an item... :rage::gun:

Your docs under the Basic tutorial for `Updating Items`:

>> Updates to table items are supported too, even atomic updates. Here is an example of atomically updating the view count of an item:
```python
>>>>> thread_item.update_item('views', 1, action='add')
```

A couple of things. It appears as though your `update_item` on the `Connection` class is using `AttributeUpdates`, which [according to Amazon](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#API_UpdateItem_RequestSyntax), is a legacy parameter. Do you plan to update the logic to use `ExpressionAttributeNames` and `ExpressionAttributeValues`?

###### Main Question
If I have an item and I want to remove an attribute, is that even possible?
I tried `item.update_item('<attr_name>, None, action='delete')` and I get:

```python
"errorType": "UpdateError",
    "errorMessage": "Failed to update item: Parameter validation failed:\nInvalid type for parameter AttributeUpdates.pet_instructions.Value.S, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>"
```

I get the same error if I replace None with an empty string. So I give it a string of `"whatever"` because I just want to delete it:
```python
"errorType": "UpdateError",
    "errorMessage": "Failed to update item: An error occurred (com.amazon.coral.validate#ValidationException) when calling the UpdateItem operation: One or more parameter values were invalid: DELETE action with value is not supported for the type STRING"
```

So I stare at the `update_item` method for a while and don't see any way to actually use the `DELETE` action. I can't not pass the `value` in as it's a required param.
```python
def update_item(self, attribute, value, action=None, conditional_operator=None, **expected_values):
```

What does `value` expect if all I want to do is delete this attribute? I've been at this for two days straight, so It's possible I completely missed something simple.

**Comment by jlafon** [comment]
Hi there, I'm sorry to hear that about your frustration. I've just push a fix (with tests) that should allow for delete actions without the need to supply an attribute value. Would you be able to try it out and verify that the issue is resolved?

**Comment by chrisjones-brack3t** [comment]
Excellent! Thank you for the quick response. I just pulled down the `devel` branch and deletions are working. I have tested this locally so far with `dynamodb-local` and will be testing it via AWS Lambda shortly but I don't see a reason for it to not work there.

Am I correct in assuming that this package is using the legacy `AttributeUpdates` parameter? If I'm given enough time with this current project, I might be able to squeeze in some time to contribute an option for using `ExpressionAttributeNames` and `ExpressionAttributeValues`.

Lastly, what is your timeline for rolling out a new version of the package with the included deletion fix?

Thank's again for the quick response.

**Comment by jlafon** [comment]
Yes, this package is using `AttributeUpdates`, I wrote this package back when it wasn't legacy. Contributions are certainly welcome, and it would be great to see the project migrated to the new syntax.

I will cut a new release later today.
