### ISSUE TITLE
Limit is off by one on Model.query

### ISSUE THREAD

**Issue by SpacedOutScott** [jlafon/PynamoDB#95]
Passing limit into Model.query returns the incorrect # of results. Passing limit=1 returns 0, limit=2 returns 1 etc. 

I believe this to be because the function subtracts from the limit and then does a comparison to 0 before yielding. If the function did the operations in the opposite order, i believe it would work correctly (but i'm unsure of implications it has for other bits of functionality). 

As of this writing, this is the line in question: https://github.com/jlafon/PynamoDB/blob/devel/pynamodb/models.py#L571

**Comment by hadrien** [comment]
I am facing the same issue and reason given by @SpacedOutScott seems valid to me.
