### ISSUE TITLE
Pynamo's session handling doesn't handle ConnectionError failures

### ISSUE THREAD

**Issue by ryan-lane** [jlafon/PynamoDB#98]
When a ConnectionError is through from botocore, the error is raised all the way through. Pynamo should catch the error and re-make the connection, then retry the request.

**Comment by pior** [comment]
@ryan-lane this is probably related to #72. You can freeze to version 1.4.2 to revert to botocore doing all the job.

**Comment by jlafon** [comment]
I think this is a good idea. PRs are welcome.

**Comment by pior** [comment]
@jlafon Can we expect a release soon if PRs were provided for this bug and #99 ?

We are considering options for a project about to be released...

**Comment by jlafon** [comment]
@pior yes I'd be happy to push a new release

**Comment by brln** [comment]
+1, also seeing this bug in production.

**Comment by dkarchmer** [comment]
+1. Getting random, infrequent connection errors which I am not really sure how to handle. Is there a recommended way to handle this now?

**Comment by pior** [comment]
@jlafon So finally, I won't be able to work on that.

Botocore has a lot of interesting tweaks, and good error handling. 
It seems quite weird to duplicate this into PynamoDB.

We decided to stay on 1.4.2 with some backported fixes : https://github.com/ludia/PynamoDB/commit/3cc24e7640a9cea6b6416e06b81b91f88c495681

**Comment by brln** [comment]
Has this been resolved, or are there any plans to resolve it? @pior are you saying that 1.4.2 doesn't have these problems? This is causing major problems in production for us.

**Comment by danielhochman** [comment]
ConnectionErrors are still unhandled in the current release. I expect to have a fix and a new release ready by the end of next week.

**Comment by danielhochman** [comment]
Fixed on devel. Unfortunately limits are currently broken on devel. Once they're fixed I'll cut a new release.
