### ISSUE TITLE
Pynamo's session handling doesn't handle failure cases from the metadata service

### ISSUE THREAD

**Issue by ryan-lane** [jlafon/PynamoDB#99]
There's a rare but serious condition that can occasionally occur in AWS's metadata service where it fails to return IAM role credentials briefly. There's other situations where the metadata service is briefly unavailable, where it either times out or it's unreachable. Unfortunately, botocore eats exceptions for these conditions (with a logging.debug statement :cry:) and returns None, as if no credentials exist. Pynamo caches the broken session, which causes all future requests to fail with no credentials errors.

When pynamo gets errors for no credentials it should re-establish the boto session to attempt to re-fetch the IAM credentials from the metadata service.

**Comment by pior** [comment]
We likely hit the same issue a few weeks ago in production. 

I have no way to confirm it, but there was no other apparent reason except a glitch with the temporary credentials.

**Comment by jlafon** [comment]
I've hit the situation as well in more than one language. I may be able to implement this in the coming weeks, but of course PRs are welcome.
